blogTitle = "Your Title Here"
subTitle = "your subtitle here"
blogUrl = "http://whatever.com"
authorName = "David Konsumer"
authorBio = "Written by <strong>David Konsumer</strong> who lives and works in Portland and makes rad stuff. You should follow him on <a href='https://twitter.com/davidkonsumer'>Twitter</a> &amp; <a href='https://github.com/konsumer'>Github</a>"
linkPrefix = "/gatsby-starter-drunkenblog"
# gaCode = "UA-0000000-0"
# disqusShortname = "yoursite"
# kommentsCode = "00000000-0000-0000-0000-000000000000"